#!/bin/sh

set -e

case "$1" in
  purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
    # remove only installed files
    rm -fr /usr/ppc-amigaos/SDK/clib2

;;

*)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
;;
esac

#DEBHELPER#

exit 0