name: Compile clib4
description: "Compile clib4 with gcc for AmigaOS 4"

inputs:
  spe:
    description: 'Compile with SPE'
    required: false
    default: "no"
  git_tag:
    description: 'Git tag to use'
    required: true

runs:
  using: "composite"
  steps:
    - name: compiling
      # if: ${{ inputs.spe != 'yes' }}
      run: |
        cd /opt/code && \
        make -j1 -f GNUmakefile.os4 OS=os4 GITTAG=${{ inputs.git_tag }}
    # - name: compiling SPE
    #   if: ${{ inputs.spe == 'yes' }}
    #   run: |
    #     cd /opt/code && \
    #     make -j1 -f GNUmakefile.os4 OS=os4 SPE=yes GITTAG=${{ inputs.git_tag }}