name: Release to OS4Depot
description: "Release clib4 to OS4Depot"

inputs:
  git_tag:
    description: 'Git tag to use'
    required: false

runs:
  using: "composite"
  steps:
    - name: Prepare OS4Depot release
      run: |
        mkdir os4depot-release
        cp clib4-${{ inputs.git_tag }}.lha ./os4depot-release/clib4.lha
        cp ./os4depot.readme ./os4depot-release/clib4_lha.readme
        sed -i "s/VERSION_TAG/${{ inputs.git_tag }}/" ./os4depot-release/os4depot.readme
        sed -i "s/OS4DEPOT_PASSPHRASE/${{ secrets.OS4DEPOT_PASSPHRASE }}/" ./os4depot-release/clib4_lha.readme

    - name: Release on OS4Depot
      uses: SamKirkland/FTP-Deploy-Action@v4.4.0
      with:
        server: os4depot.net
        port: 21
        username: ftp
        password: 
        server-dir: ./upload
        local-dir: /opt/code/os4depot-release/
    
    - name: Clear the OS4Depot release folder
      run: |
        rm -rf os4depot-release