name: Make a new release

on:
  release:
    branches:
      - master
    types: 
      - published

jobs:
  compile-ppc:
    name: Build for PowerPC cpus
    uses: ./.github/workflows/_compile.yml
    with:
      git_tag: ${{ github.event.release.tag_name }}
      gcc: 11
      spe: "no"

  compile-spe:
    name: Build for PowerPC SPE cpus
    uses: ./.github/workflows/_compile.yml
    with:
      git_tag: ${{ github.event.release.tag_name }}
      gcc: 6
      spe: "yes"
