name: Merge into main branches
on:
  pull_request:
    branches:
      - master
      - development
    types:
      - closed

jobs:
  compile-ppc:
    name: Build for PowerPC cpus
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    container:
      image: walkero/amigagccondocker:os4-gcc11
      volumes:
        - '${{ github.workspace }}:/opt/code'
    steps:
      - name: Pull code
        uses: actions/checkout@v4

      - name: Compile clib4
        uses: ./.github/actions/compile
        with:
          spe: "no"

      - name: Create the release archive
        run: make -f GNUmakefile.os4 release

  compile-spe:
    name: Build for PowerPC SPE cpus
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    container:
      image: walkero/amigagccondocker:os4-gcc6
      volumes:
        - '${{ github.workspace }}:/opt/code'
    steps:
      - name: Pull code
        uses: actions/checkout@v4

      - name: Compile clib4
        uses: ./.github/actions/compile
        with:
          spe: "yes"

      - name: Create the release archive
        run: make -f GNUmakefile.os4 release

  announcements:
    needs: [compile-ppc, compile-spe]
    name: Notify on Discord on successful PR merge
    runs-on: ubuntu-latest
    steps:
    - name: PR notification
      uses: hunghg255/action-notifications@master
      with:
        discord_webhook: https://discord.com/api/webhooks/${{ secrets.DISCORD_ANNOUNCEMENTS_ID }}/${{ secrets.DISCORD_ANNOUNCEMENTS_TOKEN }}
        title: "Deploy to ${{ github.event.pull_request.base.ref }}"
        description: "Check it out at: ${{ github.event.pull_request.html_url }}"
