name: Build with Docker
on:
  push:
    branches:
      - master
      - actions-cicd
  pull_request:
  workflow_dispatch:

jobs:
  run:
    name: Build latest code
    runs-on: ubuntu-latest
    container:
      image: walkero/amigagccondocker:os4-gcc11-exp
      volumes:
        - '${{ github.workspace }}:/opt/code'
    steps:
      - name: Pull code
        uses: actions/checkout@v2
      - name: Compile clib4
        run: |
          cd /opt/code && \
          make -j1 -f GNUmakefile.os4 OS=os4 SHARED=no
      - name: Create the release archive
        run: make -f GNUmakefile.os4 release