name: Pull request build
on:
  pull_request:
    branches:
      - master
    types: 
      - opened
      - reopened

jobs:
  compile-ppc:
    name: Build for PowerPC cpus
    runs-on: ubuntu-latest
    container:
      image: walkero/amigagccondocker:os4-gcc11
      volumes:
        - '${{ github.workspace }}:/opt/code'
    steps:
      - name: Pull code
        uses: actions/checkout@v4

      - name: Compile clib4
        uses: ./.github/actions/compile
        with:
          spe: "no"

      - name: Create the release archive
        run: make -f GNUmakefile.os4 release

  compile-spe:
    name: Build for PowerPC SPE cpus
    runs-on: ubuntu-latest
    container:
      image: walkero/amigagccondocker:os4-gcc6
      volumes:
        - '${{ github.workspace }}:/opt/code'
    steps:
      - name: Pull code
        uses: actions/checkout@v4

      - name: Compile clib4
        uses: ./.github/actions/compile
        with:
          spe: "yes"

      - name: Create the release archive
        run: make -f GNUmakefile.os4 release